In [41]:
import pandas as pd
import numpy as np
from configs.config import *
import joblib

RANDOM_SEED = 42

### Preprocessing data before fiting Logistic regression

---

In [28]:
df = pd.read_csv(PROCESSED_PATH)

df.drop(columns=['SK_ID_CURR', 'AMT_CREDIT', 'AMT_INCOME_TOTAL'], inplace=True)

Drop AMT_INCOME_TOTAL and AMT_INCOME_TOTAL as we took log of both in feature engineering (reduce collinearity by dropping). SK_ID_CURR shouldn't be threated as feature at all.

In [8]:
nan_df = pd.DataFrame({
    'Count': df.isna().sum(),
    'pct': df.isna().mean() * 100
})

nan_df = nan_df[nan_df['Count'] > 0].sort_values('pct', ascending=False).reset_index()
nan_df

                        index   Count        pct
0    prev_cc_recent_loan_rate  277153  90.127833
1           prev_cc_cost_mean  256415  83.384009
2          prev_cc_cost_worst  256415  83.384009
3      prev_cc_loan_rate_mean  256415  83.384009
4     prev_cc_loan_rate_worst  256415  83.384009
..                        ...     ...        ...
212      annuity_income_ratio      12   0.003902
213  credit_per_family_member       2   0.000650
214           CNT_FAM_MEMBERS       2   0.000650
215  income_per_family_member       2   0.000650
216    DAYS_LAST_PHONE_CHANGE       1   0.000325

[217 rows x 3 columns]

In [9]:
cat_features = df.select_dtypes('object').apply(pd.Series.nunique, axis=0)

for num, name in zip(cat_features, cat_features.index):
    if num <= 2:
        df[name] = df[name].astype('category').cat.codes.replace(-1, np.nan)

df = pd.get_dummies(df)

Fill missing values for cliens without enquiries to Credit Bureau

In [10]:
X = df.drop(columns='TARGET')
y = df['TARGET']

X = X.replace([np.inf, -np.inf], np.nan)

### Splitting data and fitting the model

---

In [11]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y,
#     test_size=0.1,
#     random_state=RANDOM_SEED,
#     stratify=y
# )

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif
from sklearn.compose import ColumnTransformer

lr_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(
        class_weight='balanced',
        max_iter=3000,
        solver='saga',
        C=0.3
    ))
])

In [ ]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)

splits = list(cv.split(X, y))
joblib.dump(splits, CV_SPLITS)

['/home/work/MLStuding/credit-scoring-ml/data/interim/cv_splits.pkl']

In [13]:
from sklearn.model_selection import cross_validate

def evaluate(pipe, X, y, cv):
    scores = cross_validate(
        pipe,
        X, y,
        cv=cv,
        scoring='roc_auc',
        return_train_score=True,
        n_jobs=-3
    )
    return {
        'train_auc': scores['train_score'].mean(),
        'cv_auc': scores['test_score'].mean(),
        'cv_std': scores['test_score'].std(),
        'fit_time': scores['fit_time'].mean()
    }

Evaluate ablation test to determine if any feature groups are redundant

In [14]:
BUREA_BALACE_COLUMNS = ['loan_duration_avg', 'loan_duration_max', 'prepaid_ratio_avg', 'defaults', 'worst_dpd', 'bad_dpd_avg',
                        'bad_dpd_cnt', 'bad_dpd_times_max', 'bigest_small_dpd', 'small_dpd_avg', 'small_dpd_cnt', 'paid_in_time_avg',
                        'paid_in_time_cnt', 'unkown_ratio_avg']
BUREAU_ALL_COLUMNS = pd.read_csv(INTERIM_BUREAU).drop(columns='SK_ID_CURR').columns
BUREAU_COLUMNS = [c for c in BUREAU_ALL_COLUMNS if c not in BUREA_BALACE_COLUMNS]
POS_CASH_COLUMNS = [c for c in X.columns if c.startswith('prev_PC')]
INSTALLMENT_COLUMNS = [c for c in X.columns if c.startswith('prev_inst')]
CREDIT_CARD_COLUMNS = [c for c in X.columns if c.startswith('prev_cc')]

EXCLUDED_PREV_COLS = (
    POS_CASH_COLUMNS +
    INSTALLMENT_COLUMNS +
    CREDIT_CARD_COLUMNS
)

PREVIOUS_APPLICATION_COLUMNS = [c for c in X.columns if c.startswith('prev') 
                                and (not c not in EXCLUDED_PREV_COLS)]

In [ ]:
X_full = X.copy()
X_no_burea_balance = X.drop(columns=BUREA_BALACE_COLUMNS)
X_no_burea = X.drop(columns=BUREAU_COLUMNS)
X_no_pos_cash = X.drop(columns=POS_CASH_COLUMNS)
X_no_inst = X.drop(columns=INSTALLMENT_COLUMNS)
X_no_cc = X.drop(columns=CREDIT_CARD_COLUMNS)
X_no_prev = X.drop(columns=PREVIOUS_APPLICATION_COLUMNS)

In [2]:
results = {}
cv = joblib.load(CV_SPLITS)

results['full'] = evaluate(lr_pipeline, X_full, y, cv)
results['no_burea_balance'] = evaluate(lr_pipeline, X_no_burea_balance, y, cv)
results['no_burea'] = evaluate(lr_pipeline, X_no_burea, y, cv)
results['no_pos_cash'] = evaluate(lr_pipeline, X_no_pos_cash, y, cv)
results['no_inst'] = evaluate(lr_pipeline, X_no_inst, y, cv)
results['no_cc'] = evaluate(lr_pipeline, X_no_cc, y, cv)
results['no_prev'] = evaluate(lr_pipeline, X_no_prev, y, cv)

pd.DataFrame(results).T.to_csv(PROJECT_ROOT / 'src/cv_results.csv')

NameError: name 'joblib' is not defined

Based on test we see that **burea balance** and **POS_CASH** related features are most week and could be droped after additional checks.

In [ ]:
cv = joblib.load(CV_SPLITS)
result = evaluate(lr_pipeline, X, y, cv)

Exception ignored in: <function ResourceTracker.__del__ at 0x74f99ee8b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x700e7e6879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x784b3f2879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75e473e8f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7eac184879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [ ]:
pd.Series(result)

train_auc       0.780147
cv_auc          0.775361
cv_std          0.004279
fit_time     2461.021984
dtype: float64

In [18]:
CORR_THRESHOLD = 0.9
corr_table = X.corr().abs()
uper_tringle = corr_table.where(np.triu(np.ones(corr_table.shape), k=1).astype(bool))

columns_drop = [c for c in uper_tringle.columns if any(uper_tringle[c] > CORR_THRESHOLD)]
print(f"{len(columns_drop)} \n {columns_drop}")

61
 ['AMT_GOODS_PRICE', 'REGION_RATING_CLIENT_W_CITY', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'TOTALAREA_MODE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'prolonged_times', 'prev_inst_duration_mean', 'prev_inst_overpay_freq_mean', 'prev_inst_delay_std_max', 'prev_inst_delay_std_std', 'prev_inst_pay_ratio_std_std', 'prev_inst_delay_recent_max', 'prev_inst_delay_recent_mean', 'prev_cc_balance_rate_max', 'prev_cc_cost_mean', 'prev_cc_loan_rate_mean', 'prev_cc_dpd_mean', 'prev_cc_zero_principal_mean', 'prev_refused_credit_max', 'prev_refused_other_cnt', 'prev_recent_applications_cnt', 'prev_prolong_mean', 'prev_loan_duration_mean', 'log_credit', 'cnt_children_capped', 'days_without_work', 'has_variability', 'days_employed_missing', 'CODE_GENDER_M', 'NAME_INCOME_TYPE_Pensioner', 'ORGANIZATION_TYPE_XNA', 'HOUSETYPE_MODE_block of flats']

In [30]:
X_corr_drop = X.drop(columns=columns_drop)

cv_collinear_droped = evaluate(lr_pipeline, X_corr_drop, y, cv)

pd.Series(cv_collinear_droped)

Exception ignored in: <function ResourceTracker.__del__ at 0x74aabd98f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76cc6e7979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x792bf789b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74bb1a3979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7dbcc54879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c4b49d979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/work/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

train_auc       0.779480
cv_auc          0.775374
cv_std          0.004239
fit_time     1961.060737
dtype: float64

Pearson correlation shows that 61 features are redundant and most of them are House related features, they have lot's of collinearity (MODE, MEDI, AVG) and highly missing. By dropping them ROC-AUC remains the same but fitting time reduced by ~20% .

In [31]:
MISSING_THRESHOLD = 0.75

nan_df = pd.DataFrame({
    'mean_missing': X_corr_drop.isna().mean()
})

high_missing_cols = nan_df[nan_df['mean_missing'] > MISSING_THRESHOLD].index.tolist()
print(f"{len(high_missing_cols)} \n {high_missing_cols}")

7
 ['prev_cc_spend_mean', 'prev_cc_interest_mean', 'prev_cc_cost_worst', 'prev_cc_loan_rate_worst', 'prev_cc_recent_balance_rate', 'prev_cc_recent_loan_rate', 'prev_grace_period_mean']

In [33]:
X_corr_miss_drop = X_corr_drop.drop(columns=high_missing_cols)

cv_missing_droped = evaluate(lr_pipeline, X_corr_miss_drop, y, cv)

pd.Series(cv_missing_droped)

Exception ignored in: <function ResourceTracker.__del__ at 0x7ec65de939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71a1e61979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7466acd979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f2d63c979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c67ee2939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

train_auc      0.779206
cv_auc         0.775167
cv_std         0.004210
fit_time     531.112157
dtype: float64

We removed all high missing features (>75%) and got huge increasing in comutation speed 2000sec before -> 500sec now, without significant drop of ROC-AUC (~0.0002).

In [39]:
C_grid = np.logspace(-3, 2, 8)
C_grid_df = {}

for c in C_grid:
    c_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(
        penalty='l2',
        class_weight='balanced',
        max_iter=3000,
        solver='saga',
        C=c
        ))
    ])
    C_grid_df[c] = evaluate(c_pipe, X_corr_miss_drop, y, cv)

experiment_name = 'lr_l2_c_search'
experiment_path = HYPERPARAM_DIR / f'{experiment_name}.csv'

pd.DataFrame(C_grid_df).T.to_csv(experiment_path)

Exception ignored in: <function ResourceTracker.__del__ at 0x74ae8118f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77ff089979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7cee1ea879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x723495f939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ceceed8f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79ffb46979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73ba69d9b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70019a08f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f52a918b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x718e09a879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x712fa32939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73a04dd9b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7df98898f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x748c3d59b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7be3b199f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77ce0448f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x711f057979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x759c57c939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x729aa2d979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7de7891979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70856c39b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b65c9a839c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e5d985939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x752f0ea8b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c1e99f939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x701e4f08f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c2fb898f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a68238939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7432ebe939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x789db8a879c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b214b88b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75612319b9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ab17bb939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7cac871939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x797fa608f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7847c228f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x712ad65939c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x798d5758f9c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7923b5f979c0>
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/home/work/miniconda3/envs/ml_env/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71206719b9c0>
Traceback (most recent call last):

            train_auc    cv_auc    cv_std    fit_time
0.001000     0.778955  0.775121  0.004093  209.970991
0.005179     0.779177  0.775193  0.004178  380.654591
0.026827     0.779203  0.775174  0.004203  494.935946
0.138950     0.779206  0.775168  0.004210  505.096503
0.719686     0.779207  0.775167  0.004210  580.924565
3.727594     0.779207  0.775166  0.004210  631.437270
19.306977    0.779207  0.775166  0.004210  633.856853
100.000000   0.779207  0.775166  0.004210  650.446580